language: objective-c
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - pod install
script:
  - xctool -workspace HIT\ Pinboard.xcworkspace -scheme HIT\ Pinboard -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
